name: Python package
on:
    workflow_dispatch:
    
    push:
        tags:
            - 'v*.*'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
                python-version: '3.11'
            
          - name: Set up Poetry
            shell: bash
            run:  |
                pip install poetry==1.6.1
            
          - name: Install dependencies
            shell: bash
            run:  |
                poetry install
            
          - name: Build and publish to PyPI
            shell: bash
            run:  |
                poetry config pypi-token.pypi ${{  secrets.PYPI_TOKEN  }}
                poetry publish --build
